-- MySQL Script generated by MySQL Workbench
-- Thu Oct  9 19:05:53 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projet_cube2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projet_cube2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projet_cube2` DEFAULT CHARACTER SET utf8 ;
USE `projet_cube2` ;

-- -----------------------------------------------------
-- Table `projet_cube2`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projet_cube2`.`Users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `hash_password` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projet_cube2`.`Conversations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projet_cube2`.`Conversations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `main_user_id` INT NOT NULL,
  `recipient_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `main_user_idx` (`main_user_id` ASC) VISIBLE,
  INDEX `recipient_user_idx` (`recipient_id` ASC) VISIBLE,
  CONSTRAINT `main_user`
    FOREIGN KEY (`main_user_id`)
    REFERENCES `projet_cube2`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `recipient_user`
    FOREIGN KEY (`recipient_id`)
    REFERENCES `projet_cube2`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projet_cube2`.`Messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projet_cube2`.`Messages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sender_id` INT NOT NULL,
  `content` VARCHAR(45) NOT NULL,
  `sent_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `conversation_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `sender_id_idx` (`sender_id` ASC) VISIBLE,
  INDEX `conversation_idx` (`conversation_id` ASC) VISIBLE,
  CONSTRAINT `sender`
    FOREIGN KEY (`sender_id`)
    REFERENCES `projet_cube2`.`Users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `conversation`
    FOREIGN KEY (`conversation_id`)
    REFERENCES `projet_cube2`.`Conversations` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
